import LegalPage from "../../../components/legal/LegalPage";

export const metadata = {
  title: "Terms & Conditions — Epigroww Global",
  description:
    "Terms governing your access to and use of the Epigroww Global website and services. Published under the Information Technology Act, 2000.",
  alternates: { canonical: "/terms-and-conditions" },
};

const sections = [
  {
    id: "document-status",
    heading: "Document Status & Legal Authority",
    body: (
      <>
        <p>
          This document constitutes an electronic record under the Information Technology Act, 2000, and the rules
          made thereunder, as applicable, and the amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000.
        </p>
        <p>
          This electronic record is generated by a computer system and does not require any physical or digital
          signature. It is published in accordance with the provisions of Rule 3(1) of the Information Technology
          (Intermediaries Guidelines) Rules, 2011, which require the publication of rules, regulations, privacy
          policy and terms of use for access or usage of the Platform.
        </p>
      </>
    ),
  },
  {
    id: "platform-ownership",
    heading: "Platform Ownership",
    body: (
      <>
        <p>
          The Platform is owned and operated by <strong>Epigroww Global Private Limited</strong>, a company
          incorporated under the Companies Act, with its registered office at the address below.
        </p>
        <div className="lp-callout">
          <span className="lp-callout-label">Registered office</span>
          <p>206, Royal Trade Center, Khurram Nagar, Lucknow, Uttar Pradesh – 226022</p>
          <p>
            <strong>Website:</strong>{" "}
            <a href="https://epigrowwglobal.com" target="_blank" rel="noopener noreferrer">
              https://epigrowwglobal.com
            </a>
          </p>
        </div>
      </>
    ),
  },
  {
    id: "binding-nature",
    heading: "Binding Nature of these Terms",
    body: (
      <>
        <p>
          By merely accessing, browsing or otherwise using the Platform, you indicate your agreement to all the terms
          and conditions outlined here, including the policies referenced in them. These constitute your binding
          obligations to the Platform Owner.
        </p>
        <p>
          Any conflicting terms proposed by you are expressly rejected. These Terms of Use may be modified at any
          time without assigning any reason; please review the page periodically to stay informed.
        </p>
      </>
    ),
  },
  {
    id: "user-obligations",
    heading: "User Obligations",
    body: (
      <ul>
        <li>Provide truthful, accurate and complete information when registering or interacting with the Platform.</li>
        <li>Bear responsibility for all activities that take place under your account.</li>
        <li>Independently verify the suitability of the services for your particular needs.</li>
        <li>Not use the Platform or services for any unlawful, illegal or forbidden purpose.</li>
        <li>Pay the charges associated with the services you avail.</li>
      </ul>
    ),
  },
  {
    id: "warranties",
    heading: "Disclaimer of Warranties",
    body: (
      <p>
        Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness,
        performance, completeness or suitability of the information and materials offered on this Platform. You
        acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude
        liability for any such inaccuracies or errors to the fullest extent permitted by law.
      </p>
    ),
  },
  {
    id: "intellectual-property",
    heading: "Intellectual Property",
    body: (
      <p>
        You will not have any authority to claim any intellectual property rights, title or interest in the Platform's
        contents. The contents include, but are not limited to, the design, layout, look, graphics and code of the
        Platform. Unauthorised reproduction is prohibited and may give rise to a claim for damages or constitute a
        criminal offence.
      </p>
    ),
  },
  {
    id: "indemnification",
    heading: "Indemnification",
    body: (
      <p>
        You shall indemnify and hold harmless the Platform Owner, its associated entities, group companies, officers,
        directors, agents and employees from any claim or demand, or actions including reasonable attorney's fees,
        made by any third party or penalty imposed due to or arising out of your breach of these Terms, the Privacy
        Policy or any other policy, or your violation of any law or the rights of a third party.
      </p>
    ),
  },
  {
    id: "third-party-links",
    heading: "Third-Party Links",
    body: (
      <p>
        The Platform may contain links to other third-party websites. When you access these links, you will be
        governed by the terms of use, privacy policy and other policies applicable to such third-party websites. The
        Platform Owner is not responsible for the content or practices of those websites.
      </p>
    ),
  },
  {
    id: "liability",
    heading: "Liability Limitations & Force Majeure",
    body: (
      <>
        <p>
          Your use of our services and the Platform is solely and entirely at your own risk and discretion, for which
          we shall not be liable to you in any manner. You are required to independently assess and ensure that the
          services meet your requirements.
        </p>
        <p>
          We shall not be liable for any failure to perform an obligation under these Terms if such performance is
          prevented, hindered or delayed by a force majeure event, and in such case our obligations will be suspended
          for so long as the force majeure event continues.
        </p>
      </>
    ),
  },
  {
    id: "governing-law",
    heading: "Governing Law & Jurisdiction",
    body: (
      <p>
        These Terms — and any dispute or claim arising out of or in connection with them — shall be governed by and
        construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms
        shall be subject to the exclusive jurisdiction of the courts in Lucknow, Uttar Pradesh.
      </p>
    ),
  },
  {
    id: "contact",
    heading: "Contact",
    body: (
      <p>
        All concerns or communications relating to these Terms must be communicated to us using the contact
        information provided on this Platform. You can reach us through the{" "}
        <a href="/contact">contact page</a>.
      </p>
    ),
  },
];

export default function TermsAndConditionsPage() {
  return (
    <LegalPage
      kicker="Legal · 02 Terms"
      eyebrow="— Legal"
      title="Terms & Conditions"
      lastUpdated="May 2026"
      intro="The terms governing your access to and use of the Epigroww Global Platform. Please read them carefully — by using the Platform you agree to be bound by them."
      sections={sections}
    />
  );
}
